export interface Card{
  topic: string,
  latitud: number,
  longitud: number,
  nivelAlerta: number,
  nivelPrecaucion: number,
  nombre: string,
  humedad: number,
  temperatura: number,
  nivelCauce: number,
  velocidadCauce: number,
  precipitacion: number,
  humedad2: number,
  temperatura2: number,
  nivelCauce2: number,
  velocidadCauce2: number,
  precipitacion2: number,
  fecha: Date,
}
